#A simple short list of DNS servers to run tests against

- country: US
  ip: 8.8.8.8
  name: google-public-dns-a.google.com
- country: US
  ip: 8.8.4.4
  name: google-public-dns-b.google.com
- country: US
  ip: 208.67.222.222
  name: resolver1.opendns.com
- country: US
  ip: 208.67.220.220
  name: resolver2.opendns.com
- country: US
  ip: 208.67.220.123
  name: resolver2-fs.opendns.com
- country: US
  ip: 208.67.220.222
  name: resolver4.opendns.com
- country: US
  ip: 208.67.222.123
  name: resolver1-fs.opendns.com
- country: US
  ip: 208.67.222.220
  name: resolver3.opendns.com
- ip: 128.243.103.175
  country: GB
  name: "!postec.nottingham.ac.uk"
